version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      [
        'start-dev'
      ]
    ports:
      - 8080:8080
