// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PhaseTwo.AuthServices.Sdk.Kiota.Admin.Admin.Users.Item.Orgs.Item.Roles;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PhaseTwo.AuthServices.Sdk.Kiota.Admin.Admin.Users.Item.Orgs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \{realm}\users\{userId}\orgs\{orgId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithOrgItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The roles property</summary>
        public global::PhaseTwo.AuthServices.Sdk.Kiota.Admin.Admin.Users.Item.Orgs.Item.Roles.RolesRequestBuilder Roles
        {
            get => new global::PhaseTwo.AuthServices.Sdk.Kiota.Admin.Admin.Users.Item.Orgs.Item.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="WithOrgItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrgItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{realm}/users/{userId}/orgs/{orgId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="WithOrgItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrgItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{realm}/users/{userId}/orgs/{orgId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
