version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      [
        'start-dev',
        '--import-realm',
        '--log-level=DEBUG,org.hibernate:info,org.keycloak.transaction.JtaTransactionWrapper:info,org.keycloak.services.scheduled.ScheduledTaskRunner:info',
        '--log-console-color=true'
      ]
    volumes:
      - ./KeycloakConfiguration/:/opt/keycloak/data/import/
    ports:
      - 8080:8080
