// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Keycloak.AuthServices.Sdk.Kiota.Admin.Models
{
    #pragma warning disable CS1591
    public enum DecisionEffect
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PERMIT")]
        #pragma warning disable CS1591
        PERMIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DENY")]
        #pragma warning disable CS1591
        DENY,
        #pragma warning restore CS1591
    }
}
