// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Keycloak.AuthServices.Sdk.Kiota.Admin.Models
{
    #pragma warning disable CS1591
    public class RolesRepresentation : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The application property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation_application? Application { get; set; }
#nullable restore
#else
        public Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation_application Application { get; set; }
#endif
        /// <summary>The client property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation_client? Client { get; set; }
#nullable restore
#else
        public Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation_client Client { get; set; }
#endif
        /// <summary>The realm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RoleRepresentation>? Realm { get; set; }
#nullable restore
#else
        public List<Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RoleRepresentation> Realm { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation"/> and sets the default values.
        /// </summary>
        public RolesRepresentation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "application", n => { Application = n.GetObjectValue<Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation_application>(Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation_application.CreateFromDiscriminatorValue); } },
                { "client", n => { Client = n.GetObjectValue<Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation_client>(Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation_client.CreateFromDiscriminatorValue); } },
                { "realm", n => { Realm = n.GetCollectionOfObjectValues<Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RoleRepresentation>(Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RoleRepresentation.CreateFromDiscriminatorValue)?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation_application>("application", Application);
            writer.WriteObjectValue<Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RolesRepresentation_client>("client", Client);
            writer.WriteCollectionOfObjectValues<Keycloak.AuthServices.Sdk.Kiota.Admin.Models.RoleRepresentation>("realm", Realm);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
