// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Keycloak.AuthServices.Sdk.Kiota.Admin.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WorkflowRepresentation : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cancelInProgress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CancelInProgress { get; set; }
#nullable restore
#else
        public string CancelInProgress { get; set; }
#endif
        /// <summary>The concurrency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowConcurrencyRepresentation? Concurrency { get; set; }
#nullable restore
#else
        public global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowConcurrencyRepresentation Concurrency { get; set; }
#endif
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The if property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? If { get; set; }
#nullable restore
#else
        public string If { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The on property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? On { get; set; }
#nullable restore
#else
        public string On { get; set; }
#endif
        /// <summary>The restartInProgress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RestartInProgress { get; set; }
#nullable restore
#else
        public string RestartInProgress { get; set; }
#endif
        /// <summary>The schedule property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowScheduleRepresentation? Schedule { get; set; }
#nullable restore
#else
        public global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowScheduleRepresentation Schedule { get; set; }
#endif
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowStateRepresentation? State { get; set; }
#nullable restore
#else
        public global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowStateRepresentation State { get; set; }
#endif
        /// <summary>The steps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowStepRepresentation>? Steps { get; set; }
#nullable restore
#else
        public List<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowStepRepresentation> Steps { get; set; }
#endif
        /// <summary>The with property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.MultivaluedHashMapStringString? With { get; set; }
#nullable restore
#else
        public global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.MultivaluedHashMapStringString With { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowRepresentation"/> and sets the default values.
        /// </summary>
        public WorkflowRepresentation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowRepresentation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowRepresentation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowRepresentation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cancelInProgress", n => { CancelInProgress = n.GetStringValue(); } },
                { "concurrency", n => { Concurrency = n.GetObjectValue<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowConcurrencyRepresentation>(global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowConcurrencyRepresentation.CreateFromDiscriminatorValue); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "if", n => { If = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "on", n => { On = n.GetStringValue(); } },
                { "restartInProgress", n => { RestartInProgress = n.GetStringValue(); } },
                { "schedule", n => { Schedule = n.GetObjectValue<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowScheduleRepresentation>(global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowScheduleRepresentation.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetObjectValue<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowStateRepresentation>(global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowStateRepresentation.CreateFromDiscriminatorValue); } },
                { "steps", n => { Steps = n.GetCollectionOfObjectValues<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowStepRepresentation>(global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowStepRepresentation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "with", n => { With = n.GetObjectValue<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.MultivaluedHashMapStringString>(global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.MultivaluedHashMapStringString.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cancelInProgress", CancelInProgress);
            writer.WriteObjectValue<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowConcurrencyRepresentation>("concurrency", Concurrency);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("if", If);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("on", On);
            writer.WriteStringValue("restartInProgress", RestartInProgress);
            writer.WriteObjectValue<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowScheduleRepresentation>("schedule", Schedule);
            writer.WriteObjectValue<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowStateRepresentation>("state", State);
            writer.WriteCollectionOfObjectValues<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.WorkflowStepRepresentation>("steps", Steps);
            writer.WriteObjectValue<global::Keycloak.AuthServices.Sdk.Kiota.Admin.Models.MultivaluedHashMapStringString>("with", With);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
