// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Keycloak.AuthServices.Sdk.Admin.Models {
    public enum DecisionStrategy {
        [EnumMember(Value = "AFFIRMATIVE")]
        AFFIRMATIVE,
        [EnumMember(Value = "UNANIMOUS")]
        UNANIMOUS,
        [EnumMember(Value = "CONSENSUS")]
        CONSENSUS,
    }
}
