// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Keycloak.AuthServices.Sdk.Admin.Models {
    public enum PolicyEnforcementMode {
        [EnumMember(Value = "ENFORCING")]
        ENFORCING,
        [EnumMember(Value = "PERMISSIVE")]
        PERMISSIVE,
        [EnumMember(Value = "DISABLED")]
        DISABLED,
    }
}
