### YamlMime:ManagedReference
items:
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  commentId: N:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  id: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  children:
  - Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.PerClientConfigDescriptionGetResponse
  - Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.PerClientConfigDescriptionRequestBuilder
  langs:
  - csharp
  - vb
  name: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  nameWithType: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  type: Namespace
  assemblies:
  - Keycloak.AuthServices.Sdk.Kiota
references:
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.PerClientConfigDescriptionGetResponse
  commentId: T:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.PerClientConfigDescriptionGetResponse
  parent: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.PerClientConfigDescriptionGetResponse.html
  name: PerClientConfigDescriptionGetResponse
  nameWithType: PerClientConfigDescriptionGetResponse
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.PerClientConfigDescriptionGetResponse
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.PerClientConfigDescriptionRequestBuilder
  commentId: T:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.PerClientConfigDescriptionRequestBuilder
  parent: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.PerClientConfigDescriptionRequestBuilder.html
  name: PerClientConfigDescriptionRequestBuilder
  nameWithType: PerClientConfigDescriptionRequestBuilder
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.PerClientConfigDescriptionRequestBuilder
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  commentId: N:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  href: Keycloak.html
  name: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  nameWithType: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
  spec.csharp:
  - uid: Keycloak
    name: Keycloak
    href: Keycloak.html
  - name: .
  - uid: Keycloak.AuthServices
    name: AuthServices
    href: Keycloak.AuthServices.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk
    name: Sdk
    href: Keycloak.AuthServices.Sdk.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota
    name: Kiota
    href: Keycloak.AuthServices.Sdk.Kiota.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms
    name: Realms
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication
    name: Authentication
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
    name: PerClientConfigDescription
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.html
  spec.vb:
  - uid: Keycloak
    name: Keycloak
    href: Keycloak.html
  - name: .
  - uid: Keycloak.AuthServices
    name: AuthServices
    href: Keycloak.AuthServices.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk
    name: Sdk
    href: Keycloak.AuthServices.Sdk.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota
    name: Kiota
    href: Keycloak.AuthServices.Sdk.Kiota.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms
    name: Realms
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication
    name: Authentication
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription
    name: PerClientConfigDescription
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.PerClientConfigDescription.html
