### YamlMime:ManagedReference
items:
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  commentId: N:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  id: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  children:
  - Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings.SettingsRequestBuilder
  langs:
  - csharp
  - vb
  name: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  nameWithType: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  type: Namespace
  assemblies:
  - Keycloak.AuthServices.Sdk.Kiota
references:
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings.SettingsRequestBuilder
  commentId: T:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings.SettingsRequestBuilder
  parent: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings.SettingsRequestBuilder.html
  name: SettingsRequestBuilder
  nameWithType: SettingsRequestBuilder
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings.SettingsRequestBuilder
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  commentId: N:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  href: Keycloak.html
  name: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  nameWithType: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
  spec.csharp:
  - uid: Keycloak
    name: Keycloak
    href: Keycloak.html
  - name: .
  - uid: Keycloak.AuthServices
    name: AuthServices
    href: Keycloak.AuthServices.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk
    name: Sdk
    href: Keycloak.AuthServices.Sdk.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota
    name: Kiota
    href: Keycloak.AuthServices.Sdk.Kiota.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms
    name: Realms
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients
    name: Clients
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz
    name: Authz
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer
    name: ResourceServer
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
    name: Settings
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings.html
  spec.vb:
  - uid: Keycloak
    name: Keycloak
    href: Keycloak.html
  - name: .
  - uid: Keycloak.AuthServices
    name: AuthServices
    href: Keycloak.AuthServices.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk
    name: Sdk
    href: Keycloak.AuthServices.Sdk.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota
    name: Kiota
    href: Keycloak.AuthServices.Sdk.Kiota.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms
    name: Realms
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients
    name: Clients
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz
    name: Authz
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer
    name: ResourceServer
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings
    name: Settings
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Clients.Item.Authz.ResourceServer.Settings.html
