### YamlMime:ManagedReference
items:
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  commentId: N:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  id: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  children:
  - Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.ConfigDescriptionRequestBuilder
  langs:
  - csharp
  - vb
  name: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  nameWithType: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  type: Namespace
  assemblies:
  - Keycloak.AuthServices.Sdk.Kiota
references:
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.ConfigDescriptionRequestBuilder
  commentId: T:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.ConfigDescriptionRequestBuilder
  parent: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.ConfigDescriptionRequestBuilder.html
  name: ConfigDescriptionRequestBuilder
  nameWithType: ConfigDescriptionRequestBuilder
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.ConfigDescriptionRequestBuilder
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  commentId: N:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  href: Keycloak.html
  name: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  nameWithType: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
  spec.csharp:
  - uid: Keycloak
    name: Keycloak
    href: Keycloak.html
  - name: .
  - uid: Keycloak.AuthServices
    name: AuthServices
    href: Keycloak.AuthServices.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk
    name: Sdk
    href: Keycloak.AuthServices.Sdk.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota
    name: Kiota
    href: Keycloak.AuthServices.Sdk.Kiota.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms
    name: Realms
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication
    name: Authentication
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
    name: ConfigDescription
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.html
  spec.vb:
  - uid: Keycloak
    name: Keycloak
    href: Keycloak.html
  - name: .
  - uid: Keycloak.AuthServices
    name: AuthServices
    href: Keycloak.AuthServices.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk
    name: Sdk
    href: Keycloak.AuthServices.Sdk.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota
    name: Kiota
    href: Keycloak.AuthServices.Sdk.Kiota.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms
    name: Realms
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication
    name: Authentication
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
    name: ConfigDescription
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.html
