### YamlMime:ManagedReference
items:
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  commentId: N:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  id: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  children:
  - Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item.WithProviderItemRequestBuilder
  langs:
  - csharp
  - vb
  name: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  nameWithType: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  type: Namespace
  assemblies:
  - Keycloak.AuthServices.Sdk.Kiota
references:
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item.WithProviderItemRequestBuilder
  commentId: T:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item.WithProviderItemRequestBuilder
  parent: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item.WithProviderItemRequestBuilder.html
  name: WithProviderItemRequestBuilder
  nameWithType: WithProviderItemRequestBuilder
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item.WithProviderItemRequestBuilder
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  commentId: N:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  href: Keycloak.html
  name: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  nameWithType: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
  spec.csharp:
  - uid: Keycloak
    name: Keycloak
    href: Keycloak.html
  - name: .
  - uid: Keycloak.AuthServices
    name: AuthServices
    href: Keycloak.AuthServices.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk
    name: Sdk
    href: Keycloak.AuthServices.Sdk.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota
    name: Kiota
    href: Keycloak.AuthServices.Sdk.Kiota.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms
    name: Realms
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication
    name: Authentication
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
    name: ConfigDescription
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item.html
  spec.vb:
  - uid: Keycloak
    name: Keycloak
    href: Keycloak.html
  - name: .
  - uid: Keycloak.AuthServices
    name: AuthServices
    href: Keycloak.AuthServices.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk
    name: Sdk
    href: Keycloak.AuthServices.Sdk.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota
    name: Kiota
    href: Keycloak.AuthServices.Sdk.Kiota.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms
    name: Realms
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication
    name: Authentication
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription
    name: ConfigDescription
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.ConfigDescription.Item.html
