### YamlMime:ManagedReference
items:
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  commentId: N:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  id: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  children:
  - Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item.ConfigItemRequestBuilder
  langs:
  - csharp
  - vb
  name: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  nameWithType: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  type: Namespace
  assemblies:
  - Keycloak.AuthServices.Sdk.Kiota
references:
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item.ConfigItemRequestBuilder
  commentId: T:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item.ConfigItemRequestBuilder
  parent: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item.ConfigItemRequestBuilder.html
  name: ConfigItemRequestBuilder
  nameWithType: ConfigItemRequestBuilder
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item.ConfigItemRequestBuilder
- uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  commentId: N:Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  href: Keycloak.html
  name: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  nameWithType: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  fullName: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
  spec.csharp:
  - uid: Keycloak
    name: Keycloak
    href: Keycloak.html
  - name: .
  - uid: Keycloak.AuthServices
    name: AuthServices
    href: Keycloak.AuthServices.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk
    name: Sdk
    href: Keycloak.AuthServices.Sdk.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota
    name: Kiota
    href: Keycloak.AuthServices.Sdk.Kiota.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms
    name: Realms
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication
    name: Authentication
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions
    name: Executions
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config
    name: Config
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item.html
  spec.vb:
  - uid: Keycloak
    name: Keycloak
    href: Keycloak.html
  - name: .
  - uid: Keycloak.AuthServices
    name: AuthServices
    href: Keycloak.AuthServices.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk
    name: Sdk
    href: Keycloak.AuthServices.Sdk.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota
    name: Kiota
    href: Keycloak.AuthServices.Sdk.Kiota.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin
    name: Admin
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms
    name: Realms
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication
    name: Authentication
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions
    name: Executions
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config
    name: Config
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.html
  - name: .
  - uid: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item
    name: Item
    href: Keycloak.AuthServices.Sdk.Kiota.Admin.Admin.Realms.Item.Authentication.Executions.Item.Config.Item.html
